//------------------------------------------------------------------------------
// <copyright file="MainWindow.xaml.cs" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Microsoft.Samples.Kinect.BodyAnalysis
{
    internal class CsvData
    {
        internal static List<string> Fields()
        {
            return new List<string>() {
                "Time",
                "SpineBase (3D) X",
                "SpineBase (3D) Y",
                "SpineBase (3D) Z",
                "SpineBase (2D) X",
                "SpineBase (2D) Y",
                "SpineMid (3D) X",
                "SpineMid (3D) Y",
                "SpineMid (3D) Z",
                "SpineMid (2D) X",
                "SpineMid (2D) Y",
                "Neck (3D) X",
                "Neck (3D) Y",
                "Neck (3D) Z",
                "Neck (2D) X",
                "Neck (2D) Y",
                "Head (3D) X",
                "Head (3D) Y",
                "Head (3D) Z",
                "Head (2D) X",
                "Head (2D) Y",
                "ShoulderLeft (3D) X",
                "ShoulderLeft (3D) Y",
                "ShoulderLeft (3D) Z",
                "ShoulderLeft (2D) X",
                "ShoulderLeft (2D) Y",
                "ElbowLeft (3D) X",
                "ElbowLeft (3D) Y",
                "ElbowLeft (3D) Z",
                "ElbowLeft (2D) X",
                "ElbowLeft (2D) Y",
                "WristLeft (3D) X",
                "WristLeft (3D) Y",
                "WristLeft (3D) Z",
                "WristLeft (2D) X",
                "WristLeft (2D) Y",
                "HandLeft (3D) X",
                "HandLeft (3D) Y",
                "HandLeft (3D) Z",
                "HandLeft (2D) X",
                "HandLeft (2D) Y",
                "ShoulderRight (3D) X",
                "ShoulderRight (3D) Y",
                "ShoulderRight (3D) Z",
                "ShoulderRight (2D) X",
                "ShoulderRight (2D) Y",
                "ElbowRight (3D) X",
                "ElbowRight (3D) Y",
                "ElbowRight (3D) Z",
                "ElbowRight (2D) X",
                "ElbowRight (2D) Y",
                "WristRight (3D) X",
                "WristRight (3D) Y",
                "WristRight (3D) Z",
                "WristRight (2D) X",
                "WristRight (2D) Y",
                "HandRight (3D) X",
                "HandRight (3D) Y",
                "HandRight (3D) Z",
                "HandRight (2D) X",
                "HandRight (2D) Y",
                "HipLeft (3D) X",
                "HipLeft (3D) Y",
                "HipLeft (3D) Z",
                "HipLeft (2D) X",
                "HipLeft (2D) Y",
                "KneeLeft (3D) X",
                "KneeLeft (3D) Y",
                "KneeLeft (3D) Z",
                "KneeLeft (2D) X",
                "KneeLeft (2D) Y",
                "AnkleLeft (3D) X",
                "AnkleLeft (3D) Y",
                "AnkleLeft (3D) Z",
                "AnkleLeft (2D) X",
                "AnkleLeft (2D) Y",
                "FootLeft (3D) X",
                "FootLeft (3D) Y",
                "FootLeft (3D) Z",
                "FootLeft (2D) X",
                "FootLeft (2D) Y",
                "HipRight (3D) X",
                "HipRight (3D) Y",
                "HipRight (3D) Z",
                "HipRight (2D) X",
                "HipRight (2D) Y",
                "KneeRight (3D) X",
                "KneeRight (3D) Y",
                "KneeRight (3D) Z",
                "KneeRight (2D) X",
                "KneeRight (2D) Y",
                "AnkleRight (3D) X",
                "AnkleRight (3D) Y",
                "AnkleRight (3D) Z",
                "AnkleRight (2D) X",
                "AnkleRight (2D) Y",
                "FootRight (3D) X",
                "FootRight (3D) Y",
                "FootRight (3D) Z",
                "FootRight (2D) X",
                "FootRight (2D) Y",
                "SpineShoulder (3D) X",
                "SpineShoulder (3D) Y",
                "SpineShoulder (3D) Z",
                "SpineShoulder (2D) X",
                "SpineShoulder (2D) Y",
                "HandTipLeft (3D) X",
                "HandTipLeft (3D) Y",
                "HandTipLeft (3D) Z",
                "HandTipLeft (2D) X",
                "HandTipLeft (2D) Y",
                "ThumbLeft (3D) X",
                "ThumbLeft (3D) Y",
                "ThumbLeft (3D) Z",
                "ThumbLeft (2D) X",
                "ThumbLeft (2D) Y",
                "HandTipRight (3D) X",
                "HandTipRight (3D) Y",
                "HandTipRight (3D) Z",
                "HandTipRight (2D) X",
                "HandTipRight (2D) Y",
                "ThumbRight (3D) X",
                "ThumbRight (3D) Y",
                "ThumbRight (3D) Z",
                "ThumbRight (2D) X",
                "ThumbRight (2D) Y",
            };
        }
    }
}
